#myellow calibration

config_commands: [
"VNWRG,06,0", # Stop Asynch
"VNRFS", # Restore factory resets
"VNWRG,06,0", # Stop Asynch (default msg is YMR reg6_14, 40 Hz)
"VNWRG,35,0,0,0,0", # VPE Disabled
"VNWRG,36,5,5,5,0,0,0,0,0,0", # trust (5) in mags and no adaptive tuning or filtering (IF VPE Off, is irrelevant.)
"VNWRG,44,0,1,5", # Turn OFF real-time mag calibration algorithm and output compensation)
"VNWRG,26,0,0,-1,1,0,0,0,-1,0", # Reference Frame (Sensor to Body)
"VNWRG,83,1,1,0,0,1000,2016.1,+43.933137,+15.444171,+100.000", # Lisbon
# "VNWRG,23,1,0,0,0,1,0,0,0,1,-0.0805,-0.0318,0.0197",  # Calibration made on 20160510 with HF modem
# "VNWRG,23,1,0,0,0,1,0,0,0,1,-0.0270,-0.0949,-0.0022", # Calibration made on 20160530
# "VNWRG,23,1,0,0,0,1,0,0,0,1,0.0124,-0.0788,0.0057", # Calibration made on BIOGRAD 20161017
"VNWRG,23,1.0728,0.0192,0.0136,0.0192,0.9806,-0.0175,0.0136,-0.0175,0.8348,-0.0186,0.0383,0.0205", # Calibration made on 20161121 Sines HF and MF modems
"VNWNV", # Write settings to  memory
"VNRST", # Reset the Kalman Filter
]

check_commands: [
"VNWRG,07,10", # Asynch data output rate 10 [Hz]
"VNWRG,06,14", # (reg6_14) YMR, Magnet, Accel [m/s^2], Gyros [rad/s]
"VNRRG,21", # Read Mag and Grav model vectors
"VNRRG,23", # Read Calibration mode
"VNRRG,26", # Install matrix
"VNRRG,35", # VPE Basic Control
"VNRRG,36", # Basic Magnetometers Configuration
"VNRRG,37", # Advanced Magnetometers Configuration
"VNRRG,83", # Read Mag and Grav model cfg and position/date
]
